// <auto-generated />
using System;
using Authorization.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Authorization.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117151208_ChangeEntities")]
    partial class ChangeEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Authorization.DAL.Entities.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Identities");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Authorization.DAL.Entities.Patient", b =>
                {
                    b.HasBaseType("Authorization.DAL.Entities.Identity");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Authorization.DAL.Entities.Worker", b =>
                {
                    b.HasBaseType("Authorization.DAL.Entities.Identity");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("Authorization.DAL.Entities.Patient", b =>
                {
                    b.HasOne("Authorization.DAL.Entities.Identity", null)
                        .WithOne()
                        .HasForeignKey("Authorization.DAL.Entities.Patient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Authorization.DAL.Entities.Worker", b =>
                {
                    b.HasOne("Authorization.DAL.Entities.Identity", null)
                        .WithOne()
                        .HasForeignKey("Authorization.DAL.Entities.Worker", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
